nMeet/urls.py
from . import views
from django.urls import path
from django.contrib.auth.decorators import login_required
urlpatterns = [
				path('',login_required(views.nMeetViewDashboard.as_view()),name='default'),
				path('login/',views.nMeetLogin,name='nMeetLogin'),
				path('logout/', login_required(views.nMeetLogout),name='nMeetLogout'),
				path('dashboard/',login_required(views.nMeetViewDashboard.as_view()),name='nMeetDashboard'),
				path('enterFigures/', login_required(views.nMeetEnterFigures.as_view()),name='nMeetEnterFigures'),
				path('chat/',login_required(views.nMeetChat.as_view()),name='nMeetChat'),
				path('refreshChat/',login_required(views.refreshChat),name='nMeetRefreshChat'),
				path('clearDashboard/',login_required(views.nMeetClearDashboard),name='nMeetClearDashboard'),
				path('nMeetClearChat/',login_required(views.nMeetClearChat),name='nMeetClearChat'),
				path('saveDashboard/',login_required(views.nMeetSaveDashboard),name='nMeetSaveDashboard'),
                path('cancelFigs/',login_required(views.nMeetCancelFigs.as_view()),name="nMeetCancelFigs"),
                path('upload_summary_file',login_required(views.nMeet_upload_summary_file),name="nMeet_upload_summary_file"),
			]

rAsset/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('redirect.urls')),
    path('asset/',include('aMgnt.urls')),
    path('nMeet/',include('nMeet.urls')),
    path('sMnt/',include('sMnt.urls')),
]

sMnt/urls.py
from . import views
from django.urls import path, include
from django.contrib.auth.decorators import login_required

urlpatterns = [
				# path('',login_required(views.addRecord),name='default'),
				path('addRecord/',login_required(views.sMntAddRecord),name='sMntAddRecord'),
				path('sMntDashboard/',login_required(views.sMntDashboard.as_view()),name='sMntDashboard'),
				path('cancelStatements/',login_required(views.sMntCancelStatments),name="sMntCancelStatments"),
				path('genReport/',login_required(views.sMntGenReport),name="sMntGenReport"),
				path('setQuantity/',login_required(views.sMntSetQuantity),name="sMntSetQuantity"),
                		path('sMntSearch/',login_required(views.sMntSearch),name="sMntSearch"),
				path('sMntDelSmnt', login_required(views.sMntDelSmnt.as_view()),name="sMntDelSmnt"),
			]

from django.urls import re_path
# urlpatterns += [
    # re_path(r'^accounts/login/', views.asset_login, name='login'),
    # re_path(r'logout', views.asset_logout, name='logout'),
# ]

nMeet/models.py
#Model definitions
from django.db import models
from django_timestamps.timestamps import TimestampsModel
#Note branch fields in dashboard and chat tables are intentionally not implemented as foreign keys.
#This is because the application is very small and these tables are cleared at the end of the meeting.
#Thus, they will not put immense strain on the db or affect performance.
class Dashboard(TimestampsModel,models.Model):
	branch = models.CharField(max_length=20)
	teller_or_operator = models.CharField(max_length=15)
	debit = models.CharField(max_length=20)
	credit = models.CharField(max_length=20)
	updated = models.BooleanField(default=False)
class Chat(TimestampsModel,models.Model):
	branch = models.CharField(max_length=20)
	text = models.CharField(max_length=200)
class Cancelled(models.Model):
	id_of_cancelled_fig = models.BigIntegerField(blank=False,null=False)

nMeet/forms.py
from django import forms

class UploadFileForm(forms.Form):
    file = forms.FileField()

nMeet/views.py
######################## Utility methods ######################
import datetime
date = datetime.datetime.now().strftime('%Y')
#################  Dependecies for core app  ####################
import json
from .forms import *
from .models import *
from django.views import View
from django.db.models import Q
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.http import FileResponse, JsonResponse, HttpResponse
from django.contrib.auth.hashers import make_password, check_password
############# Dependencies for genreating dashboard figures as excel file#########
import io
from docx import Document
from docx.table import Table
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from cherrypy import log
#############################
def nMeetLogin(request):
	try:
		if request.method == 'GET': #serve login page
			if request.user.is_authenticated : #except if already logged_in
				return redirect('dashboard')
			else :
				context = {'message':'', 'error':'none', 'date':date}
				return render(request, "nMeetLogin.html", context)
		if request.method == 'POST': #validate user
			user = authenticate(username=request.POST.get('username'), password=request.POST.get('password') )
			if user is not None :
				login(request, user, backend=user.backend)
				requested_page = request.GET.get('next')
				if requested_page is not None :
					return redirect(requested_page)
				else :
					return redirect('nMeetDashboard')
			else:
				context = {'message' : 'Incorrect Username or Password', 'error':'visible', 'date':date}
				return render(request, 'nMeetLogin.html',  context)
	except Exception as e: #catch any errors just to be extra safe.
		return redirect('nMeetLogin')
def nMeetLogout(request):
	from django.contrib.auth import logout
	logout(request)
	return redirect('nMeetLogin')
def http_response(status_code):
	response = HttpResponse()
	response.status_code = status_code
	return response
class nMeetViewDashboard(View):
	def get(self, request, *args, **kwargs):
		#Return the ui for the dashboard page.
		try:
			return render(request,'nMeetDashboard.html',{'date':date,'dashboard':True})
		#Incase error accessing db.
		except Exception as e:
			log('\n\n\n'+str(e)+'\n\n\n')
			return render(request,'nMeetDashboard.html',{'date':date,'dashboard':False})
	def post(self, request, *args, **kwargs):
		#Returns n newest dashboard entries when ajax request made. n = request.POST['length'].
		try:
			dashboard = []
			if request.POST['length'] == "-1":
				dashboard_buffer = Dashboard.objects.all()
			else:
				dashboard_buffer = Dashboard.objects.all()[:int(request.POST['length'])]
			for row in dashboard_buffer:
				if row.updated is True:
					time_sent = row.updated_at.strftime('%H:%M:%S')
					dashboard.append([row.id,row.branch,row.teller_or_operator,row.debit,row.credit,time_sent,"updated"])
				else:
					time_sent = row.created_at.strftime('%H:%M:%S')
					dashboard.append([row.id,row.branch,row.teller_or_operator,row.debit,row.credit,time_sent,"not_updated"]) 
			return JsonResponse({'dashboard':dashboard,'cancelled':[cancelled.id_of_cancelled_fig for cancelled in Cancelled.objects.all()]})
		except Exception as e:
			log('\n\n\n\n'+str(e)+'\n\n\n\n')
			return http_response(status_code=500)
def nMeetClearDashboard(request):
	try:
		if authenticate(username='Admin', password=request.POST['admin_password']) is None:
			return JsonResponse({'success':False})
		else:
			for row in Dashboard.objects.all():
				row.delete()
			for cancelled in Cancelled.objects.all():
				cancelled.delete()
			return JsonResponse({'success':True})
	except Exception as e:
		log('\n\n\n'+str(e)+'\n\n\n')
		return JsonResponse({'success':False})
def nMeetSaveDashboard(request):
	try:
		document = Document()
		from docx.enum.text import WD_ALIGN_PARAGRAPH
		document.add_heading('ROKEL END OF DAY PROCESSING \n' + str( datetime.datetime.now().strftime('%d-%m-%Y') ), 0).alignment = WD_ALIGN_PARAGRAPH.CENTER
		query = ~Q(username="Admin") & ~Q(username="beod") & ~Q(username="IT SUPPORT") 
		users = User.objects.filter(query)
		branches_in_order = ['FSSST','FCLOCK','BO','KENEMA','FWIA','FHO','FWILF','KOIDU','MOYAMBA','PUJEHUN','FCX','MAKENI','FCHAR','KABALA','KAILAHUN','FWILK', 'FJUBA']
		for user in users:
			if user.username not in branches_in_order:
				branches_in_order.append(user.username)
		for branch_name in branches_in_order:
			branch = branch_name 
			document.add_heading(branch + ' Figures').alignment = WD_ALIGN_PARAGRAPH.CENTER
			rows = Dashboard.objects.filter(branch=branch)
			if bool(rows):
				table = document.add_table(len(rows)+1,4)
				table.cell(0,0).add_paragraph('Teller or Operator')
				table.cell(0,1).add_paragraph('Debit')
				table.cell(0,2).add_paragraph('Credit')
				table.cell(0,3).add_paragraph('Time Sent')
				table.alignment = WD_TABLE_ALIGNMENT.CENTER
				for index,row in enumerate(rows):
					cells = table.row_cells(index+1)
					for i,cell in enumerate(cells):
						if i == 0:
							cell.add_paragraph(row.teller_or_operator)
						elif i == 1:
							cell.add_paragraph(row.debit)
						elif i == 2:
							cell.add_paragraph(row.credit)
						elif i == 3:
							if row.updated_at != None:
								cell.add_paragraph(row.updated_at.strftime('%H:%M:%S'))
							else:
								cell.add_paragraph(row.created_at.strftime('%H:%M:%S')) 
			else:
				document.add_paragraph('No figures sent for ' + branch).alignment = WD_ALIGN_PARAGRAPH.CENTER
		f = io.BytesIO()
		document.save(f)
		f.seek(0)
		return FileResponse(f, as_attachment=True, filename='ROKEL END OF DAY PROCESSING FIGURES-' + datetime.datetime.now().strftime('%d-%m-%Y') +'.docx')
	except Exception as e:
		log('\n\n\n\n' + str(e) + '\n\n\n\n')
		return redirect('generic500page',redirect_url='error')
class nMeetEnterFigures(View):
	template = 'nMeetEnterFigures.html'
	def get(self, request, *args, **kwargs):
		return render(request,self.template,{'date':date})
	def post(self, request, *args, **kwargs):
		try:
			already_existing_row = Dashboard.objects.filter(branch=request.user.username,teller_or_operator=request.POST.get('teller_or_operator'))
			if bool ( already_existing_row ):
				already_existing_row[0].credit = request.POST.get('credit').replace(" ","").replace("\t","")
				already_existing_row[0].debit = request.POST.get('debit').replace(" ","").replace("\t","")
				already_existing_row[0].updated = True
				already_existing_row[0].save()
			else:
				row = Dashboard(branch=request.user.username,teller_or_operator=request.POST.get('teller_or_operator'),debit=request.POST.get('debit').replace(" ","").replace("\t",""),credit=request.POST.get('credit').replace(" ","").replace("\t",""))
				row.save()
			response = HttpResponse()
			response.status_code = 200
			return response
		except Exception as e:
			log('\n\n\n'+str(e)+'\n\n\n')
			response = HttpResponse()
			response.status_code = 500
			return response
class nMeetChat(View):
	def get(self, request, *args, **kwargs):
		chat = [[message.created_at.strftime('%Y-%m-%d %H:%M:%S'),message.branch,message.text,message.id] for message in Chat.objects.all()]
		return JsonResponse({'chat':chat})
	def post(self, request, *args, **kwargs):
		#Add chat and return success message.
		try:
			if request.POST.get('text') is not None and request.POST.get('text') != '':
				chat = Chat(branch=request.user.username, text=request.POST.get('text'))
				chat.save()
			return http_response(status_code=200)
		except Exception as e:
			log('\n\n\n'+str(e)+'\n\n\n')
			return http_response(status_code=503)
def refreshChat(request):
	#chat_buffer holds the last 50 rows of the chat.
	chat_buffer = [[message.created_at.strftime('%Y-%m-%d %H:%M:%S'),message.branch,message.text,message.id] for message in Chat.objects.all().order_by('id')[:50]]
	return JsonResponse({'chat_buffer':chat_buffer})
def nMeetClearChat(request):
	for message in Chat.objects.all():
		message.delete()
	response = HttpResponse()
	response.status_code = 200
	return response
class nMeetCancelFigs(View):
	template = 'cancelFigs.html'
	branches = User.objects.filter(~Q(username="Admin") & ~Q(username="beod") & ~Q(username="IT SUPPORT"))
	def get(self,request,*args,**kwargs):
		try:
			if request.user.username == 'Admin' or request.user.username == 'IT SUPPORT':  
				return render(request,self.template,{'date':date, 'error':'false', 'success':'false', 'message':'', 'branches':self.branches})
			else:
				return redirect('nMeetDashboard')
		except Exception as e:
			log('\n\n\n'+ str(e)+ '\n\n\n')
			return render(request,self.template,{'date':date, 'error':'true', 'success':'false','message':'An error was encountered loading the page. Please contact admin.'})
	def post(self,request,*args,**kwargs):
		try:
			row = Dashboard.objects.filter(branch=request.POST['branch'],teller_or_operator=request.POST['teller_or_operator'])
			if bool(row):
				cancelled = Cancelled(id_of_cancelled_fig=row[0].id)
				cancelled.save()
				row[0].delete()
				return render(request, self.template, {'branches':self.branches,'date':date, 'success':'true', 'error':'false','message':'The figs for '+ str(row[0].branch)+ ' ' + str(row[0].teller_or_operator) +' have been deleted successfully.'})
			else:
				return render(request,self.template,{'branches':self.branches,'date':date,'success':'false','error':'true','message':'There are no figs for that teller / operator.'})
		except Exception as e:
			log('\n\n\n'+str(e)+'\n\n\n')
			return render(request, self.template, {"date":date, 'error':'true', 'message':'There was a problem deleting the selected figures. Please contact admin or IT CENTER for support.', 'success':'false'})
def nMeet_upload_summary_file(request):
	try:
		if request.method == "POST":
			figures = json.loads(request.POST['tellers_and_operators'])
			for teller_or_operator in figures: 

nMeet/templates/cancelFigs.html
{% extends "nMeetBase.html" %} 
{%load static%}

{%block AdditionalAssets%} 
<link rel="stylesheet" type="text/css" href="{% static 'aMgnt/assets/my_css/semantic-UI-hot-fix.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'aMgnt/assets/my_css/toastr-position-hot-fix.css' %}">
<style>
  .ui.blue.button {background-color: #024fcc; color: white;}
  body{ overflow-y: scroll; }
</style>
{%endblock AdditionalAssets%}

{%block content%}
{%if user.username == 'Admin' or user.username == 'IT SUPPORT'%}                   
<div class='container-fluid'>
	<h1>Cancel Figures</h1>
	<hr>
	<div class="ui segments container">
		<div class="ui segment">
			<form id="cancel_figures_form" method="POST">
				{%csrf_token%}
				<div class="row"> 
					<label>Branch:</label>
			        <select class="form-control" name="branch" required="">
			        	{%for branch in branches%}
                           <option value = '{{branch}}'>{{branch}}</option>
                        {%endfor%}
			        </select>
			        <label>Teller or operator:</label>
                   <select class="form-control" name="teller_or_operator" required="">
			        	{%for num in '111111111111111'|make_list%}
				        	{%if forloop.counter < 10%}
				        	<option value="CA TELLER{{forloop.counter}}">CA TELLER{{forloop.counter}}</option>
				        	{%else%}
					        <option value="CA TELLER{{forloop.counter}}">CA TELLER{{forloop.counter}}</option>
				        	{%endif%}
			        	{%endfor%}
			        	{%for num in '1111111111'|make_list%}
				        	{%if forloop.counter < 10%}
				        	<option value="CA OPERATOR{{forloop.counter}}">CA OPERATOR{{forloop.counter}}</option>
				        	{%else%}
				        	<option value="CA OPERATOR{{forloop.counter}}">CA OPERATOR{{forloop.counter}}</option>
				        	{%endif%}
			        	{%endfor%}
			        	{%for num in '1111111111'|make_list%}
				        	{%if forloop.counter < 10%}
				        	<option value="SA TELLER{{forloop.counter}}">SA TELLER{{forloop.counter}}</option>
				        	{%else%}
				        	<option value="SA TELLER{{forloop.counter}}">SA TELLER{{forloop.counter}}</option>
				        	{%endif%}
			        	{%endfor%}
			        	{%for num in '1111111111'|make_list%}
				        	{%if forloop.counter < 10%}
				        	<option value="SA OPERATOR{{forloop.counter}}">SA OPERATOR{{forloop.counter}}</option>
				        	{%else%}
				        	<option value="SA OPERATOR{{forloop.counter}}">SA OPERATOR{{forloop.counter}}</option>
				        	{%endif%}
			        	{%endfor%}
			        	{%for num in '11111'|make_list%}
				        	{%if forloop.counter < 10%}
				        	<option value="FO TELLER{{forloop.counter}}">FO TELLER{{forloop.counter}}</option>
				        	{%else%}
				        	<option value="FO TELLER{{forloop.counter}}">FO TELLER{{forloop.counter}}</option>
				        	{%endif%}
			        	{%endfor%}
			        	{%for num in '11111'|make_list%}
			        	{%if forloop.counter < 10%}
				        	<option value="FO OPERATOR{{forloop.counter}}">FO OPERATOR{{forloop.counter}}</option>
				        	{%else%}
				        	<option value="FO OPERATOR{{forloop.counter}}">FO OPERATOR{{forloop.counter}}</option>
				        	{%endif%}
			        	{%endfor%}
			        </select>
			    </div>
		        <button type="submit" id="submit" style="background-color:#00307d; color:white;" class="ui tiny button mt-2 ml-0">Submit</button>		
			</form>
		</div>
	</div>
</div>
{%endif%}
{%endblock content%}

{%block scripts%}
<script type="text/javascript">
if({{error}}){toastr.error('{{message}}');}
if({{success}}){toastr.success('{{message}}');}
</script>
{%endblock scripts%}

nMeet/templates/nMeetBase.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Rokel End of Day Processing</title>
  <!-- Rokel Icon -->
  <link rel="icon" href="{% static 'nMeet/assets/dist/img/favicon.png' %}" type="image/gif" sizes="20x20">
   <!-- Toastr -->
  <link rel="stylesheet" href=" {%static 'nMeet/assets/plugins/toastr/toastr.min.css' %}">
  <!-- DataTables -->
  <link rel="stylesheet" type="text/css" href=" {% static 'nMeet/assets/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'nMeet/assets/plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %} ">
  <link rel="stylesheet" type="text/css" href="{% static 'nMeet/assets/dt_fixedheader/FixedHeader-3.1.7/css/fixedHeader.bootstrap.min.css' %} ">
  <!-- Google Fonts -->
  <!-- <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback"> -->
  <!-- <link rel="stylesheet" href="{% static 'nMeet/assets/google_fonts/Sans_Pro.css' %}"> -->
  <!-- Font for all text -->
  <!-- <link href="https://fonts.googleapis.com/css2?family=Titillium+Web:wght@300&display=swap" rel="stylesheet"> -->
  <!-- <link rel="stylesheet" href="{% static 'nMeet/assets/google_fonts/Titillium_Web.css' %}"> -->
  <!-- Font for logout navbar link -->
  <!-- <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@200;300&display=swap" rel="stylesheet"> -->
  <!-- Font Awesome -->
  <!-- <link rel="stylesheet" href="{% static 'nMeet/assets/plugins/fontawesome-free/css/all.min.css' %}"> -->
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'nMeet/assets/dist/css/adminlte.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static 'nMeet/assets/plugins/ionicons/css/ionicons.min.css' %}">
  <!-- base style sheet -->
  <link rel="stylesheet" type="text/css" href="{% static 'nMeet/assets/plugins/base/base.css'%}">

  <link href="{%static 'aMgnt/assets/google-material-design/material-design.css'%}" rel="stylesheet">

  <!-- Semantic UI CSS -->
  <link rel="stylesheet" type="text/css" href="{% static 'nMeet/assets/themes/Semantic-UI/semantic.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'nMeet/assets/my_css/semantic-UI-hot-fix.css' %}">

  <!-- jQuery -->
  <script src="{% static 'nMeet/assets/plugins/jquery/jquery.min.js' %}"></script>
  <!-- Bootstrap 4 JS -->
  <script src="{% static 'nMeet/assets/plugins/bootstrap/js/bootstrap.bundle.min.js' %} "></script>
  <!-- AdminLTE App -->
  <!-- <script src="{% static 'nMeet/assets/dist/js/adminlte.min.js' %}"></script> -->
  <!-- jquery-validation -->
  <script src="{% static 'nMeet/assets/plugins/jquery-validation/jquery.validate.min.js' %}"></script>
  <script src="{% static 'nMeet/assets/plugins/jquery-validation/additional-methods.min.js' %}"></script>  
  <!-- Toastr -->
  <script src="{% static 'nMeet/assets/plugins/toastr/toastr.min.js' %}"></script>
  <!-- DataTables JS -->
  <script src=" {% static 'nMeet/assets/plugins/datatables/jquery.dataTables.min.js' %} "></script>
  <script src=" {% static 'nMeet/assets/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
  <script src=" {% static 'nMeet/assets/plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
  <script src=" {% static 'nMeet/assets/plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'nMeet/assets/dt_fixedheader/FixedHeader-3.1.7/js/dataTables.fixedHeader.min.js' %}"></script>

<!--                                    Semantic UI JS                                      -->
<script  src="{% static 'nMeet/assets/themes/Semantic-UI/semantic.min.js' %}"></script>

  {%block AdditionalAssets%} {%endblock AdditionalAssets%}

</head>

<body style="zoom:88%;font-size: 14px; font-family: 'Titillium Web', sans-serif; overflow-x: hidden !important; max-width: 100%;">
  <div class="ui small borderless menu">
    <div class="ui container-fluid grid">
      <div class="computer only row">
        <a class="item" href="{% url 'redirectLandingPage' %}">
            <img src="{% static 'nMeet/assets/logo/RCB.jpg' %}" style="margin-left:15px;width: 45px; height: 45px; border-radius:50%;">
        </a>
        <span class="item">Rokel End Of Day Meeting</span>
        {%if user.username != "Admin" and user.username != "IT SUPPORT"%}
        <span class="item">Branch {{user.username}}</span>
        {%else%}
        <span class="item">{{user.username}}</span>
        {%endif%}
        <div class="right menu">
            <a class="item" href="{% url 'nMeetDashboard' %}">Dashboard</a>
            {%if user.username == 'Admin' or user.username == 'IT SUPPORT'%}
            <a class="item" href="{% url 'nMeetCancelFigs' %}">Cancel Figs</a>
            {%endif%}
            {%if user.username != 'Admin' and user.username != 'IT SUPPORT'%}
              <a class="item" href="{% url 'nMeetEnterFigures' %}">Enter Figures</a>
            {%endif%}
            <a class="item" href="{% url 'nMeetLogout' %}">Logout</a>
        </div>
      </div>
       <div class="tablet mobile only row">
        <a class="item ml-3" href="{% url 'redirectLandingPage' %}">
            <img src="{% static 'nMeet/assets/logo/RCB.jpg' %}" style="width: 45px; height: 45px; border-radius:50%;">
        </a>
        <span class="item">Rokel Asset Management</span>
        <span class="item">{{user.username}}</span>
        <div class="right menu">
          <div class="menu item" style="margin-right: -20px;">
            <div class="ui floating dropdown item">
                <div class="ui grey icon button"><i class="content icon" style="color:white;"></i></div>
                <div class="menu">
                  <a class="item" href="{% url 'nMeetDashboard' %}">Dashboard</a>
                  {%if user.username == 'Admin' or user.username == 'IT SUPPORT'%}
                  <a class="item" href="{% url 'nMeetCancelFigs' %}">Cancel Figs</a>
                  {%endif%}
                  {%if user.username != 'Admin' and user.username != 'IT SUPPORT'%}
                    <a class="item" href="{% url 'nMeetEnterFigures' %}">Enter Figures</a>
                  {%endif%}
                  <hr class="mt-0 mb-0">
                  <a class="item" href="{% url 'nMeetLogout' %}">Logout</a>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <br>
  <!-- Content Wrapper. Contains page content -->
  {% block content %} {% endblock content %}
  <!-- /.content-wrapper -->
<hr>
<footer style=" text-align: center; width: 100%;">
    Copyright &copy; 
              {{date}}
             RCBank.
    All rights reserved.
</footer>
<script type="text/javascript">$(".dropdown").dropdown()</script>
</body>
</html>

{%block scripts%} {%endblock scripts%}

nMeet/templates/nMeetUploadFigures.html
{% extends "nMeetBase.html" %} 
{%load static%}

{%block AdditionalAssets%} 
<link rel="stylesheet" type="text/css" href="{% static 'aMgnt/assets/my_css/semantic-UI-hot-fix.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'aMgnt/assets/my_css/toastr-position-hot-fix.css' %}">
<style>
  .ui.blue.button {background-color: #024fcc; color: white;}
  body{ overflow-y: scroll; }
</style>
{%endblock AdditionalAssets%}

{%block content%}
<div class='container-fluid'>
	<h1>Upload Figures</h1>
	<hr class="mt-1">
	<h2 class="ui center aligned icon header">
	  <i class="upload icon"></i>
	  <span>Select A File</span>
	</h2>
	<br>
	<div class="ui three column grid mb-5">
		<div class="col"></div>
		<div class="col">
				<div class="ui three column grid">
					<div class="col"></div>
			<div class="col mt-2">
				<form id="uploadFiguresForm" method="post" enctype="multipart/form-data">
					{%csrf_token%}
					{{fileForm}}
					<div class="mt-3 ui three column grid">
						<div class="col"></div>
						<div class="col">
							<button type="submit" class="ml-1 ui tiny blue button" id="upload-button">Upload</button>
						</div>
						<div class="col"></div>
					</div>
				</form>
			</div>
			<div class="col"></div>
		</div>
		</div>
		<div class="col"></div>
	</div>
</div>

<div class="ui basic modal">
  <div class="ui icon header">
    You must first select a file to upload.
  </div>
</div>
{%endblock content%}

{%block scripts%}
<script type="text/javascript">
	{%if success%}
	toastr.success('{{message}}')
	{%elif error%}
	toastr.error('{{message}}')
	{%endif%}
	//position file input widget properly and remove required attr.
	$('#id_file').attr('class','ml-5')
	$('#id_file').attr('accept','text/plain')
	$('#id_file').removeAttr('required')
	//Remove file input label.
	$('label[for="id_file"]').remove()
	//Check if a file has been selected.
	$('#uploadFiguresForm').submit((e)=>{ if($('#id_file').val()==''){$('.ui.basic.modal').modal('show'); e.preventDefault();}else{$('#upload-button').attr('class','ml-1 ui tiny button'); $('#upload-button').text('Uploading...');}});
</script>
{%endblock scripts%}